---
latitude: 40.71993
longitude: -73.98799
map_zoom: 12
name: Hotel On Rivington
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 107 Rivington Street
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10002'
_hotel_id: HOT269
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
